name: PHP Codeception Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests.yml@main
    with:
      module-id: breakingnews
      php:
        - "7.4"
        - "8.0"